@echo off
set "VCTools=D:\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64"
set "SDKLib=C:\Program Files (x86)\Windows Kits\10\lib\10.0.26100.0\um\x64"
set "LinkCmd=%VCTools%\link.exe"

"%LinkCmd%" ^
  /OUT:"build\bin\x64\Release\dinput8.dll" ^
  /INCREMENTAL:NO ^
  /NOLOGO ^
  /DYNAMICBASE:NO ^
  /NXCOMPAT ^
  /MANIFEST ^
  /MANIFESTUAC:"level='asInvoker' uiAccess='false'" ^
  /manifest:embed ^
  /DEBUG ^
  /PDB:"build\bin\x64\Release\dinput8.pdb" ^
  /SUBSYSTEM:WINDOWS ^
  /OPT:REF ^
  /OPT:ICF ^
  /TLBID:1 ^
  /MACHINE:X64 ^
  /IGNORE:4702 ^
  /LTCG ^
  /DLL ^
  /IMPLIB:"build\bin\x64\Release\dinput8.lib" ^
  "build\obj\x64\Release\client\binds.obj" ^
  "build\obj\x64\Release\client\cheat.obj" ^
  "build\obj\x64\Release\client\command.obj" ^
  "build\obj\x64\Release\client\console.obj" ^
  "build\obj\x64\Release\client\custom_server.obj" ^
  "build\obj\x64\Release\client\dedicated_server.obj" ^
  "build\obj\x64\Release\client\denuvo.obj" ^
  "build\obj\x64\Release\client\discord.obj" ^
  "build\obj\x64\Release\client\exception.obj" ^
  "build\obj\x64\Release\client\filesystem.obj" ^
  "build\obj\x64\Release\client\fob_gui.obj" ^
  "build\obj\x64\Release\client\fob_target.obj" ^
  "build\obj\x64\Release\client\fobs.obj" ^
  "build\obj\x64\Release\client\game_console.obj" ^
  "build\obj\x64\Release\client\gameplay.obj" ^
  "build\obj\x64\Release\client\hashes.obj" ^
  "build\obj\x64\Release\client\flow_manager.obj" ^
  "build\obj\x64\Release\client\input.obj" ^
  "build\obj\x64\Release\client\http.obj" ^
  "build\obj\x64\Release\client\io.obj" ^
  "build\obj\x64\Release\client\json.obj" ^
  "build\obj\x64\Release\client\main.obj" ^
  "build\obj\x64\Release\client\test.obj" ^
  "build\obj\x64\Release\client\renderer.obj" ^
  "build\obj\x64\Release\client\scripting.obj" ^
  "build\obj\x64\Release\client\object.obj" ^
  "build\obj\x64\Release\client\ui_button.obj" ^
  "build\obj\x64\Release\client\ui_element.obj" ^
  "build\obj\x64\Release\client\ui_image.obj" ^
  "build\obj\x64\Release\client\ui_list.obj" ^
  "build\obj\x64\Release\client\ui_menu.obj" ^
  "build\obj\x64\Release\client\ui_text.obj" ^
  "build\obj\x64\Release\client\ui_text_input.obj" ^
  "build\obj\x64\Release\client\ui_timer.obj" ^
  "build\obj\x64\Release\client\scheduler.obj" ^
  "build\obj\x64\Release\client\server_logging.obj" ^
  "build\obj\x64\Release\client\session.obj" ^
  "build\obj\x64\Release\client\defs.obj" ^
  "build\obj\x64\Release\client\lobby.obj" ^
  "build\obj\x64\Release\client\mutes.obj" ^
  "build\obj\x64\Release\client\ui.obj" ^
  "build\obj\x64\Release\client\vars.obj" ^
  "build\obj\x64\Release\client\directx.obj" ^
  "build\obj\x64\Release\client\d3d11_blend_state.obj" ^
  "build\obj\x64\Release\client\d3d11_buffer.obj" ^
  "build\obj\x64\Release\client\d3d11_class_instance.obj" ^
  "build\obj\x64\Release\client\d3d11_class_linkage.obj" ^
  "build\obj\x64\Release\client\d3d11_compute_shader.obj" ^
  "build\obj\x64\Release\client\d3d11_counter.obj" ^
  "build\obj\x64\Release\client\d3d11_depth_stencil_state.obj" ^
  "build\obj\x64\Release\client\d3d11_depth_stencil_view.obj" ^
  "build\obj\x64\Release\client\d3d11_device.obj" ^
  "build\obj\x64\Release\client\d3d11_device_child.obj" ^
  "build\obj\x64\Release\client\d3d11_device_context.obj" ^
  "build\obj\x64\Release\client\d3d11_domain_shader.obj" ^
  "build\obj\x64\Release\client\d3d11_geometry_shader.obj" ^
  "build\obj\x64\Release\client\d3d11_hull_shader.obj" ^
  "build\obj\x64\Release\client\d3d11_input_layout.obj" ^
  "build\obj\x64\Release\client\d3d11_pixel_shader.obj" ^
  "build\obj\x64\Release\client\d3d11_predicate.obj" ^
  "build\obj\x64\Release\client\d3d11_query.obj" ^
  "build\obj\x64\Release\client\d3d11_rasterizer_state.obj" ^
  "build\obj\x64\Release\client\d3d11_render_target_view.obj" ^
  "build\obj\x64\Release\client\d3d11_sampler_state.obj" ^
  "build\obj\x64\Release\client\d3d11_shader_resource_view.obj" ^
  "build\obj\x64\Release\client\d3d11_texture1d.obj" ^
  "build\obj\x64\Release\client\d3d11_texture2d.obj" ^
  "build\obj\x64\Release\client\d3d11_texture3d.obj" ^
  "build\obj\x64\Release\client\d3d11_unordered_access_view.obj" ^
  "build\obj\x64\Release\client\d3d11_user_defined_annotation.obj" ^
  "build\obj\x64\Release\client\d3d11_vertex_shader.obj" ^
  "build\obj\x64\Release\client\d3d11_view.obj" ^
  "build\obj\x64\Release\client\dxgi_adapter.obj" ^
  "build\obj\x64\Release\client\dxgi_device.obj" ^
  "build\obj\x64\Release\client\dxgi_device_sub_object.obj" ^
  "build\obj\x64\Release\client\dxgi_factory.obj" ^
  "build\obj\x64\Release\client\dxgi_object.obj" ^
  "build\obj\x64\Release\client\dxgi_output.obj" ^
  "build\obj\x64\Release\client\dxgi_swap_chain.obj" ^
  "build\obj\x64\Release\client\game.obj" ^
  "build\obj\x64\Release\client\component_loader.obj" ^
  "build\obj\x64\Release\client\std_include.obj" ^
  "build\obj\x64\Release\client\renderer1.obj" ^
  "build\obj\x64\Release\client\scripting1.obj" ^
  "build\obj\x64\Release\client\input1.obj" ^
  "build\obj\x64\Release\client\main1.obj" ^
  "build\obj\x64\Release\client\resource.res" ^
  "build\bin\x64\Release\asmjit.lib" ^
  "build\bin\x64\Release\curl.lib" ^
  "build\bin\x64\Release\discord-rpc.lib" ^
  "build\bin\x64\Release\DSXpp.lib" ^
  "build\bin\x64\Release\imgui.lib" ^
  "build\bin\x64\Release\libtommath.lib" ^
  "build\bin\x64\Release\libtomcrypt.lib" ^
  "build\bin\x64\Release\minhook.lib" ^
  "build\bin\x64\Release\minizip.lib" ^
  "build\bin\x64\Release\lua.lib" ^
  "build\bin\x64\Release\udis86.lib" ^
  "build\bin\x64\Release\zlib.lib" ^
  "build\bin\x64\Release\common.lib" ^
  "%SDKLib%\Shlwapi.lib" ^
  "%SDKLib%\Crypt32.lib" ^
  "%SDKLib%\kernel32.lib" ^
  "%SDKLib%\user32.lib" ^
  "%SDKLib%\gdi32.lib" ^
  "%SDKLib%\winspool.lib" ^
  "%SDKLib%\comdlg32.lib" ^
  "%SDKLib%\advapi32.lib" ^
  "%SDKLib%\shell32.lib" ^
  "%SDKLib%\ole32.lib" ^
  "%SDKLib%\oleaut32.lib" ^
  "%SDKLib%\uuid.lib" ^
  "%SDKLib%\odbc32.lib" ^
  "%SDKLib%\odbccp32.lib"

echo Exit code: %ERRORLEVEL%
